services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: produtos_db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"    # RabbitMQ main port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  websocket:
    build: ./servidor/websocket
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
  rest:
    build: ./servidor/rest
    ports:
      - "55556:55556"
    depends_on:
      - mongodb
      - rabbitmq

  soap:
    build: ./servidor/soap
    ports:
      - "55555:55555"
    depends_on:
      - mongodb
      - rabbitmq
  
  graphql:
    build: ./servidor/graphql
    ports:
      - "55557:55557"
    depends_on:
      - mongodb
      - rabbitmq
    
  grpc:
    build: ./servidor/grpc
    ports:
      - "55558:55558"
    depends_on:
      - mongodb
      - rabbitmq
    
  client:
    build: ./cliente
    ports:
      - "5000:5000"
    depends_on:
      - rest
      - soap
      - graphql
      - grpc