# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: livros.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'livros.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clivros.proto\x12\x06livros\x1a\x1bgoogle/protobuf/empty.proto\"E\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x0e\n\x06\x65stado\x18\x04 \x01(\t\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\x11ListBooksResponse\x12\x1b\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0c.livros.Book\")\n\x0b\x42ookRequest\x12\x1a\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0c.livros.Book\"$\n\x11OperationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbc\x02\n\x0cLivroService\x12>\n\tListBooks\x12\x16.google.protobuf.Empty\x1a\x19.livros.ListBooksResponse\x12/\n\x07GetBook\x12\x16.livros.GetBookRequest\x1a\x0c.livros.Book\x12<\n\nCreateBook\x12\x13.livros.BookRequest\x1a\x19.livros.OperationResponse\x12<\n\nUpdateBook\x12\x13.livros.BookRequest\x1a\x19.livros.OperationResponse\x12?\n\nDeleteBook\x12\x16.livros.GetBookRequest\x1a\x19.livros.OperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'livros_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=53
  _globals['_BOOK']._serialized_end=122
  _globals['_GETBOOKREQUEST']._serialized_start=124
  _globals['_GETBOOKREQUEST']._serialized_end=152
  _globals['_LISTBOOKSRESPONSE']._serialized_start=154
  _globals['_LISTBOOKSRESPONSE']._serialized_end=202
  _globals['_BOOKREQUEST']._serialized_start=204
  _globals['_BOOKREQUEST']._serialized_end=245
  _globals['_OPERATIONRESPONSE']._serialized_start=247
  _globals['_OPERATIONRESPONSE']._serialized_end=283
  _globals['_LIVROSERVICE']._serialized_start=286
  _globals['_LIVROSERVICE']._serialized_end=602
# @@protoc_insertion_point(module_scope)
